server:
  port: 8082

keycloak-server:
  host-name: keycloak.rimaubank.co.id
  uri: http://${keycloak-server.host-name}:8000/auth/realms/rimaubank
  openid-uri: ${keycloak-server.uri}/protocol/openid-connect

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak-server.uri}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true

esb:
  host-name: esb.rimaubank.co.id
  url:
    account-service: http://${esb.host-name}:9010/account-service
    transfer-service: http://${esb.host-name}:9010/transfer-service

logging:
  level:
    org.springframework.security: warn
