server:
  port: 8082

keycloak-server:
  uri: http://127.0.0.1:8080/realms/maybank
  openid-uri: ${keycloak-server.uri}}/protocol/openid-connect

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-server.uri}

logging:
  level:
    org.springframework.security: trace